name: Terraform Format

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'

      - name: Terraform Format
        run: terraform fmt --recursive

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-format Terraform files
          commit_options: '--no-verify'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}