name: Terraform Format

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'

      - name: Terraform Format
        run: terraform fmt --recursive

      - name: Copy formatted files
        run: |
          cp -r . $GITHUB_WORKSPACE/temp
          rm -rf .
          mv $GITHUB_WORKSPACE/temp/* .
          rm -rf $GITHUB_WORKSPACE/temp

      - name: Git Status Before
        run: git status

      - name: Git Add Changes
        run: git add .

      - name: Git Commit Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Auto-format Terraform files"

      - name: Git Push Changes
        run: git remote set-url --push origin https://orionex93:$TOKEN@github.com/GitHubactionstest.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
