name: Terraform Format

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'

      - name: Terraform Format
        run: terraform fmt --recursive

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-format Terraform files"
          git remote set-url --push origin https://orionex93:$TOKEN@github.com/GitHubactionstest.git
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}




